# pytorch基础

### 张量

In [10]:
import torch
import numpy as np
# 初始化张量
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

# 使用Numpy array 创建张量
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# 使用已有的张量
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n {x_rand} \n")

# 通过随机或常量创建
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor:\n {rand_tensor} \n")
print(f"Ones Tensor:\n {ones_tensor} \n")
print(f"Zeros Tensor:\n {zeros_tensor}\n")

# 张量的属性
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

# 张量操作
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
else:
  print("cuda is not available")

# numpy 的索引和切片操作
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

# 链接张量
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

# 运算操作
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

#
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

#
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2771, 0.9184],
        [0.1933, 0.6790]]) 

Random Tensor:
 tensor([[0.0292, 0.6192, 0.3593],
        [0.8061, 0.5230, 0.3844]]) 

Ones Tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
cuda is not available
First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
